# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  test:
    desc: Print a greeting message
    vars:
      DOCKER_PATH: '{{.DOCKER_PATH | default "podman"}}'
    cmds:
      - |
        {{ .DOCKER_PATH }} compose up -d
        trap "{{ .DOCKER_PATH }} compose down" EXIT
        go test -v ./...
    silent: true
  
  oapi-codegen:
    desc: Generate Go code from OpenAPI specification
    cmds:
      - cd cms-schema && pnpm install && pnpm tsp compile .
      - go tool oapi-codegen -config oapi-codegen.yaml ./cms-schema/tsp-output/schema/openapi.yaml
