// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock_repository.go -package=content
//

// Package content is a generated GoMock package.
package content

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetTextContent mocks base method.
func (m *MockRepository) GetTextContent(ctx context.Context, key string) (ContentType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextContent", ctx, key)
	ret0, _ := ret[0].(ContentType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTextContent indicates an expected call of GetTextContent.
func (mr *MockRepositoryMockRecorder) GetTextContent(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextContent", reflect.TypeOf((*MockRepository)(nil).GetTextContent), ctx, key)
}

// PutTextContent mocks base method.
func (m *MockRepository) PutTextContent(ctx context.Context, props putTextContentDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutTextContent", ctx, props)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutTextContent indicates an expected call of PutTextContent.
func (mr *MockRepositoryMockRecorder) PutTextContent(ctx, props any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutTextContent", reflect.TypeOf((*MockRepository)(nil).PutTextContent), ctx, props)
}
