// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for ArticleStatus.
const (
	Published   ArticleStatus = "published"
	Unpublished ArticleStatus = "unpublished"
)

// Valid indicates whether the value is a known member of the ArticleStatus enum.
func (e ArticleStatus) Valid() bool {
	switch e {
	case Published:
		return true
	case Unpublished:
		return true
	default:
		return false
	}
}

// Defines values for SortOrder.
const (
	Asc  SortOrder = "asc"
	Desc SortOrder = "desc"
)

// Valid indicates whether the value is a known member of the SortOrder enum.
func (e SortOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// ArticleDetail defines model for ArticleDetail.
type ArticleDetail = ArticleMetadata

// ArticleMetadata defines model for ArticleMetadata.
type ArticleMetadata struct {
	CreatedAt    string        `json:"createdAt"`
	Pv           float32       `json:"pv"`
	Slug         string        `json:"slug"`
	Source       string        `json:"source"`
	Status       ArticleStatus `json:"status"`
	Tags         []string      `json:"tags"`
	ThumbnailUrl string        `json:"thumbnailUrl"`
	Title        string        `json:"title"`
	UpdatedAt    string        `json:"updatedAt"`
}

// ArticleStatus defines model for ArticleStatus.
type ArticleStatus string

// DeleteSuccess defines model for DeleteSuccess.
type DeleteSuccess struct {
	Message string `json:"message"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// SortOrder defines model for SortOrder.
type SortOrder string

// UpsertTextArticle defines model for UpsertTextArticle.
type UpsertTextArticle struct {
	ContentBody  string        `json:"contentBody"`
	Source       string        `json:"source"`
	Status       ArticleStatus `json:"status"`
	Tags         *[]string     `json:"tags,omitempty"`
	ThumbnailUrl string        `json:"thumbnailUrl"`
	Title        string        `json:"title"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ArticlesListParams defines parameters for ArticlesList.
type ArticlesListParams struct {
	Tag    *string        `form:"tag,omitempty" json:"tag,omitempty"`
	Status *ArticleStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int32         `form:"limit,omitempty" json:"limit,omitempty"`
	Order  *SortOrder     `form:"order,omitempty" json:"order,omitempty"`
}

// ArticlesUpsertJSONRequestBody defines body for ArticlesUpsert for application/json ContentType.
type ArticlesUpsertJSONRequestBody = UpsertTextArticle

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 記事一覧を取得
	// (GET /api/articles)
	ArticlesList(ctx *echo.Context, params ArticlesListParams) error
	// 記事を削除
	// (DELETE /api/articles/{slug})
	ArticlesDelete(ctx *echo.Context, slug string) error
	// 記事詳細を取得
	// (GET /api/articles/{slug})
	ArticlesRead(ctx *echo.Context, slug string) error
	// 記事を作成または更新
	// (PUT /api/articles/{slug})
	ArticlesUpsert(ctx *echo.Context, slug string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ArticlesList converts echo context to params.
func (w *ServerInterfaceWrapper) ArticlesList(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ArticlesListParams
	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "tag", ctx.QueryParams(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "status", ctx.QueryParams(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "order", ctx.QueryParams(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ArticlesList(ctx, params)
	return err
}

// ArticlesDelete converts echo context to params.
func (w *ServerInterfaceWrapper) ArticlesDelete(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", ctx.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ArticlesDelete(ctx, slug)
	return err
}

// ArticlesRead converts echo context to params.
func (w *ServerInterfaceWrapper) ArticlesRead(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", ctx.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ArticlesRead(ctx, slug)
	return err
}

// ArticlesUpsert converts echo context to params.
func (w *ServerInterfaceWrapper) ArticlesUpsert(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", ctx.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter slug: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ArticlesUpsert(ctx, slug)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/articles", wrapper.ArticlesList, options.OperationMiddlewares["Articles_list"]...)
	router.DELETE(options.BaseURL+"/api/articles/:slug", wrapper.ArticlesDelete, options.OperationMiddlewares["Articles_delete"]...)
	router.GET(options.BaseURL+"/api/articles/:slug", wrapper.ArticlesRead, options.OperationMiddlewares["Articles_read"]...)
	router.PUT(options.BaseURL+"/api/articles/:slug", wrapper.ArticlesUpsert, options.OperationMiddlewares["Articles_upsert"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FhPbxNHFP8qq2mPq9gEetlbED2gUoEaOEU+THaf7UG7s8vMLCW1VmJtqiYFBKJtgBaJVmrTgEqIRA60",
	"4s+Hmdg1J75CNbN/vLbXjt2Qtki9eWfn/f/93nvrFrJ9L/ApUMGR1ULcboKH9c8lJojtwikQmLjqALvu",
	"2TqyVlroQwZ1ZKEPKgPhSipZScU+BYEdLDCKaiYKmB8AEwS0YtunAqhQP8VaAMhCXDBCGyiKTMTgUkgY",
	"OMhayS/WzOyiv3oRbIEiE42asVqjVhhgAc5SmR0TBZcLxzT0VoGpY+6GjdL73A+ZDeWvBBahNjlDWpaT",
	"y5GJBG5oISLA46WK0wPMGF7Tz83QW6WYuBeYWy5AhFvuYxg4E5MxknSdgkxXHngepk6dWchuUXka1Yir",
	"U8q3nOcOaOgp80G46hLeBEcppoOngZJBVKfABQHLoW0D5+MI8IBz3ICDQ84uljn6MWM+G9cN2fF0zcm1",
	"Mr3LPhNnmQOsGDzmNjKRA9wujfdCwIGJ83BFpOkrQX1CmZO+s6ZTQOgZoA3RRNYxcxqqPXwlv1itmgcK",
	"Hg7zDtRx6ApkrdTMQxCg4PRidQavc34MCx4gN1LSjBjFTJfR5AAKqCSCHTIi1pZVupLynQTMgC2FypO0",
	"GSuh5BjlSppCBChSOgit+0lGuc1IIIhPkYU+wRSzcMEDQ8Y7snNbdjqy/VS2t2XnmexsLJ07LTsbsv1E",
	"dn6RnZ/04XrO+aL40rnTyESXgfFE8eJCdaGqUukHQHFAkIWO6yMTBVg0dQwVHJAKTkqvDxogxl3sb9/b",
	"/+O6jHf2n1/tb/0q23e6tza7r+7K+K6MX8n4vrza7j++2d9+IePvZPuGjLdkfE3Gj2V8rfvjXvf2uoyf",
	"dr/87c3m9d7zdRm/zhWq36+/7d7cywRTbUh7zbBy4LSDrKwH8TOECx0Awx4IYFzPOLgSuL4DyKpjl4PK",
	"NLLQpRCYKjfFui4Cq1aZwL20GcymJsfMQNMctJrViks8IoaM1H3mYYEsRKg4vohMxQviqVaU9YD0KQce",
	"oQIaalTOatTXLW7WyAZNMVJrAwMe+JQnKFqsVkeWBxwELrF1PSsXuUJVq2AnbytzLSujTUdxbBi455tg",
	"qH4AXBhNzA2uxg844Cwo6Y/m9HKac8noKXFhGdhlYAak703EQ8/DbC2n1QinsrlsreSYRzUlN0TVSkuN",
	"/iihqhqs46Tt3fiqu/N9xquHsv277DzSzWVXxjspA9t3uhtfv7n/c87kty/W+1txQua3LzYm8jAZ5+NM",
	"1LhS7aXAmGRJGfRlwUIoomx6Rz8stqZVbXgpmRtAJ6rHjh5AS9o5g3AjpDgUTZ+RL3L7J47evkoBT0Bs",
	"Y0p9YdQJdQwxyAw4BoNkqP6bvEontIZhcTav1BSGRmmXQ7+ccGb5JJyFVP1Hz/7c2x0fkhO59Blg531n",
	"0vAH6N9g0v9InjghRgA1CbBBOGV1u9F9cq/7YFuDcWgt623u9rdu7b980Fu/La/G2bX7sn29sLpt77/8",
	"Rrbv9H7Y623uzj0skm+hfwziupTZV9U7qd34x1w0/KmhvIyOnl6D3Wdegi2+w1F1GGcMTB0DGxQ+z5mm",
	"L6wCUCP9o8LA3MDqdeiK/8ScfV8GWspixc2HitqarRMWyvwLf6WVcS9/HdWivwIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
