// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock_repository.go -package=metadata
//

// Package metadata is a generated GoMock package.
package metadata

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetArticle mocks base method.
func (m *MockRepository) GetArticle(ctx context.Context, getArticleDTO *getArticleDTO) (*getArticleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", ctx, getArticleDTO)
	ret0, _ := ret[0].(*getArticleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockRepositoryMockRecorder) GetArticle(ctx, getArticleDTO any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockRepository)(nil).GetArticle), ctx, getArticleDTO)
}

// GetArticleTags mocks base method.
func (m *MockRepository) GetArticleTags(ctx context.Context, getArticleTagsDTO *getArticleTagsDTO) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleTags", ctx, getArticleTagsDTO)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleTags indicates an expected call of GetArticleTags.
func (mr *MockRepositoryMockRecorder) GetArticleTags(ctx, getArticleTagsDTO any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleTags", reflect.TypeOf((*MockRepository)(nil).GetArticleTags), ctx, getArticleTagsDTO)
}

// ListArticles mocks base method.
func (m *MockRepository) ListArticles(ctx context.Context, listArticlesDTO *listArticlesDTO) (*ListArticlesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticles", ctx, listArticlesDTO)
	ret0, _ := ret[0].(*ListArticlesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockRepositoryMockRecorder) ListArticles(ctx, listArticlesDTO any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*MockRepository)(nil).ListArticles), ctx, listArticlesDTO)
}

// PutArticle mocks base method.
func (m *MockRepository) PutArticle(ctx context.Context, props *putArticleDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutArticle", ctx, props)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutArticle indicates an expected call of PutArticle.
func (mr *MockRepositoryMockRecorder) PutArticle(ctx, props any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutArticle", reflect.TypeOf((*MockRepository)(nil).PutArticle), ctx, props)
}
